### PR TITLE
QVB configuration needed for reload in QVS

### PR DESCRIPTION
**Pull request by josefinestal**
If the user wants to perform a reload of an app with a load script including SSE, the SSE plugin must be configured in the Settings.ini file for QVB or the reload will fail.

### CODE REVIEW

**Comment by josefinestal** [comment]
I updated the text and removed the link to Qlik Help. If you don't have any comments on the change, I'm ready to squash and merge the commits.

**Review by qlik-aoh — APPROVED** [review]
Look like the QVB settings.ini is in a strange location.

**Comment by josefinestal** [comment]
@qlik-aoh According to the help site https://help.qlik.com/en-US/qlikview/November2017/Subsystems/Server/Content/QlikView-Server/QVSRM_Logging.htm the path I wrote is the default one. But on my machine, I have the path C:\Users\OST\AppData\Roaming\QlikTech\QlikViewBatch which I thought was also valid (I don't have a QVS installed now but I have had in the past), but I haven't got an answer from the people I've talked to. I'll try to find someone else today which hopefully knows.

**Comment by josefinestal** [comment]
@qlik-aoh I've verified that the path is correct.

**Review by kjartan-qlik — APPROVED** [review]

**Pull request merged**
